#!/usr/bin/python3

import sys
import time

def factorize(num):
	'''number(input).
	Args:
	    num: input integer.
	    Return: if the number is not a prime return a tuple
		    none if the number is prime.
	'''
	for i in range(2, int(num**0.5)+):
	    if num % i == 0:
		return (i, num//i)
	return None

if __name__ == "__main__":

	'''Reads input file.
	'''
	if len(sys.argv) != 2:
	    print("Usage: factors <file>")
	    exit()

	input_file = sys.argv[1]

	try:
	    with open(input_file, 'r') as f:
		lines = f.readlines()
	except FileNotFoundError:
	    print("Error:File not found")
	    exit()

	start_time = time.time()

	'''loops over each line and factorize'''
	for line in lines:
	    num = int(line.strip())
	    factors = factorize(num)
	    if factors:
		print(f"{num}={factors[0]}*{factors[1]}")
	'''elapsed time 5 seconds,
		exit program with an error message.
	'''
	if time.time() - start_time > 5:
	    print("Time limit exceeded")
	    exit()
